export type BiomeType = 
    | 'MANGUE' 
    | 'PARK' 
    | 'BEACH' 
    | 'INDUSTRIAL' 
    | 'RESIDENTIAL' 
    | 'WATER'
    //micro-biomas
    | 'CASA_FORTE'  
    | 'BRENNAND'
    | 'JAQUEIRA'  
    | 'RECIFE_ANTIGO'
    | 'CENTRO'  
    | 'SPORT'
    | 'NAUTICO'  
    | 'BEIRA_RIO'
    | 'GRACAS'  
    | 'AGAMENON'
    | 'OLINDA'  
    | 'ARRUDA';